name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Testar com versões LTS recomendadas

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci # Usar 'ci' para instalação limpa e rápida baseada no package-lock.json
    - name: Run linters and formatters
      run: npm run lint && npm run format:check # Adicionar scripts no package.json se necessário
    # - name: Run tests # Descomentar quando os testes forem implementados
    #   run: npm test
    - name: Build project
      run: npm run build --if-present # Executa build se o script existir

